export const TID = {
  header: {
    root: "site-header",
    logo: "brand-logo",
    navShop: "nav-shop",
    navJournal: "nav-journal",
    navFaq: "nav-faq",
    navTransparency: "nav-transparency",
    cartBtn: "cart-toggle-btn",
    accountBtn: "account-btn",
    loginBtn: "login-btn",
    logoutBtn: "logout-btn",
  },
  home: {
    hero: "home-hero",
    heroCta: "home-hero-cta",
    featuredGrid: "featured-grid",
    aiRecommendBtn: "ai-recommend-btn",
    aiRecommendResult: "ai-recommend-result",
  },
  product: {
    card: (slug) => `product-card-${slug}`,
    cardCta: (slug) => `product-card-cta-${slug}`,
    title: "pdp-title",
    price: "pdp-price",
    variantSelect: "pdp-variant-select",
    addToCart: "pdp-add-to-cart",
    ingredients: "pdp-ingredients",
    nutrition: "pdp-nutrition",
    transparency: "pdp-transparency",
  },
  shop: {
    grid: "shop-grid",
    search: "shop-search",
    sort: "shop-sort",
    categoryFilter: (slug) => `shop-cat-${slug}`,
  },
  cart: {
    drawer: "cart-drawer",
    item: (id) => `cart-item-${id}`,
    inc: (id) => `cart-inc-${id}`,
    dec: (id) => `cart-dec-${id}`,
    checkoutBtn: "cart-checkout-btn",
  },
  checkout: {
    email: "checkout-email",
    name: "checkout-name",
    phone: "checkout-phone",
    line1: "checkout-line1",
    city: "checkout-city",
    state: "checkout-state",
    pincode: "checkout-pincode",
    coupon: "checkout-coupon",
    applyCoupon: "checkout-apply-coupon",
    place: "checkout-place-order",
  },
  auth: {
    email: "auth-email",
    password: "auth-password",
    name: "auth-name",
    submit: "auth-submit",
  },
  ai: {
    fab: "ai-fab",
    input: "ai-input",
    send: "ai-send",
    log: "ai-log",
  },
  admin: {
    dashTab: "admin-tab-dashboard",
    ordersTab: "admin-tab-orders",
    catalogTab: "admin-tab-catalog",
    promotionsTab: "admin-tab-promotions",
    journalTab: "admin-tab-journal",
    auditTab: "admin-tab-audit",
  },
};
